name: Docker Build and Push

on:
  push:
    tags:
      - "*"
  workflow_dispatch:  # 手动调度
  schedule:
    - cron: '33 2 * * 0'  # 每周日凌晨 2:33 自动触发

concurrency:
  group: "docker-image"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/orgs/community/discussions/25768#discussioncomment-8053592
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:latest # ,ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
